#Application config
spring:
  application:
    name: Backend-Service

  #Database config
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/base?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:123456789}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}


  #Jpa config
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  #Mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MailAdmin}
    password: ${password-email}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#Server config
server:
  port: 8080


#Security config
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration: 86400000


#Logging config
logging:
  level:
    root: INFO
    com.example: DEBUG